language: node_js
node_js:
  - "14"
  - "16"
  - "18"

# Specify the branch to build
branches:
  only:
    - main
    - develop

# Navigate to the backend directory before running commands
before_install:
  - cd backend

# Install dependencies
install:
  - npm install

# Run tests
script:
  - ls 
  - npm run test

# Optional: Configure notifications
notifications:
  email:
    recipients:
      - 1155194577@link.cuhk.edu.hk
    on_success: always
    on_failure: always

# Optional: Cache dependencies to speed up builds
cache:
  directories:
    - backend/node_modules
